# For different named developers
developer:
  default:
    database: 
      instance_type: "db.t2.micro"
      db_type: "postgres"
  smith:
    instance_type: "t2.medium"

# Your top level domain
hosted_zone_name: "rails-aws.com"

# For Repo/Branch builds
default:
  account_id: 180190769793
redesign:
  database: 
    instance_type: db.t2.micro
    db_type: postgres
master:
  database: 
    instance_type: db.t2.micro
    db_type: postgres
