# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7c06f128f328d84d47590dbc61aed407512b8590e6f31464d62fb1fccd26a82cf712d263fb0c1b675b486bce1923fa2796f9a0d77c81ad942d07415ecde776e

test:
  secret_key_base: 20047843aa44a18000c17f0eeeb1376e9649539c9ebca7b24030c5536aaa2c0ddf47ee725bdf1a836dbc12b4b28afc248e54c132c36911e5f978f92dd00b5441

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
